ALTER TABLE "disponibilita_riders" ADD CONSTRAINT "disponibilita_riders_rider_id_profiles_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "merchant_favorites" ADD CONSTRAINT "merchant_favorites_merchant_id_profiles_id_fk" FOREIGN KEY ("merchant_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "merchant_favorites" ADD CONSTRAINT "merchant_favorites_rider_id_profiles_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "occasional_performance_receipts" ADD CONSTRAINT "occasional_performance_receipts_prenotazione_id_prenotazioni_id_fk" FOREIGN KEY ("prenotazione_id") REFERENCES "public"."prenotazioni"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prenotazioni" ADD CONSTRAINT "prenotazioni_esercente_id_esercenti_id_fk" FOREIGN KEY ("esercente_id") REFERENCES "public"."esercenti"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prenotazioni" ADD CONSTRAINT "prenotazioni_rider_id_profiles_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recensioni" ADD CONSTRAINT "recensioni_prenotazione_id_prenotazioni_id_fk" FOREIGN KEY ("prenotazione_id") REFERENCES "public"."prenotazioni"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recensioni" ADD CONSTRAINT "recensioni_esercente_id_esercenti_id_fk" FOREIGN KEY ("esercente_id") REFERENCES "public"."esercenti"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recensioni" ADD CONSTRAINT "recensioni_rider_id_profiles_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "service_requests" ADD CONSTRAINT "service_requests_merchant_id_profiles_id_fk" FOREIGN KEY ("merchant_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "service_requests" ADD CONSTRAINT "service_requests_rider_id_profiles_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;